#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="singbox_server"
PROG="/usr/bin/sing-box"
JSON_DIR="/var/etc/$CONF"

start_service() {
    config_load "$CONF"
    config_foreach start_instance "server"
}

start_instance() {
    local cfg="$1"
    local enable port
    config_get_bool enable "$cfg" "enable" 0
    [ "$enable" -eq 1 ] || return 1

    config_get port "$cfg" "port"

    mkdir -p "$JSON_DIR"
    local json_file="$JSON_DIR/$cfg.json"

    lua /usr/share/singbox_server/gen_config.lua "$cfg" "$json_file"

    if [ -f "$json_file" ]; then
        procd_open_instance "$CONF-$cfg"
        procd_set_param command "$PROG" run -c "$json_file"
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
        
        if [ -n "$port" ]; then
            iptables -I INPUT -p tcp --dport "$port" -m comment --comment "SingBox-Server-$cfg" -j ACCEPT
            iptables -I INPUT -p udp --dport "$port" -m comment --comment "SingBox-Server-$cfg" -j ACCEPT
        fi
    fi
}

stop_service() {
    iptables-save | grep -v "SingBox-Server-" | iptables-restore
    rm -rf "$JSON_DIR"
}

reload_service() {
    stop_service
    start_service
}
