#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1
PROG=/usr/bin/sing-box

start_service() {
	config_load singbox-server
	config_foreach start_instance server
}

start_instance() {
	local cfg="$1"
	config_get enabled "$cfg" enabled
	config_get config_file "$cfg" config_file
	config_get log_file "$cfg" log_file "/var/log/singbox-server_${cfg}.log"
	config_get log_level "$cfg" log_level "info"

	[ "$enabled" = "1" ] || return 0

	procd_open_instance "$cfg"
	procd_set_param command "$PROG" run -c "$config_file"
	procd_append_param command ">>$log_file" "2>&1"
	procd_set_param respawn
	procd_set_param file "$config_file"
	procd_close_instance
}

stop_service() {
	return 0
}

service_triggers() {
	procd_add_reload_trigger "singbox-server"
}
