#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

APP=/usr/share/singbox-server/app.sh

start_service() {
	[ -x "$APP" ] || return 1
	"$APP" start
}

stop_service() {
	[ -x "$APP" ] || return 0
	"$APP" stop
}

reload_service() {
	"$APP" restart
}
