# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024 luci-app-sing-box-server contributors
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for sing-box Server
LUCI_DEPENDS:=+luci-compat +luci-lua-runtime
PKG_NAME:=luci-app-sing-box-server
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=0

include $(TOPDIR)/luci.mk

# call BuildPackage - OpenWrt buildroot signature
