include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-singbox-server
PKG_VERSION:=2.0.1
PKG_RELEASE:=0

LUCI_TITLE:=LuCI support for Sing-box Server (multi-instance)
LUCI_DEPENDS:=+luci-compat +jq
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
