include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Sing-box Server (multi-instance)
LUCI_DEPENDS:=+sing-box +luci-compat
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-singbox-server
PKG_VERSION:=2.0.0
PKG_RELEASE:=0

include $(TOPDIR)/feeds/luci/luci.mk
